name: Get linked issues
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited

jobs:
  get-linked-issues:
    name: Get linked issues
    runs-on: ubuntu-latest
    steps:
      - name: Get issue numbers separated by commas
        id: get-issues
        uses: mondeja/pr-linked-issues-action@v1.1.0dev
      - name: Print issue numbers
        run: echo ${{ steps.get-issues.outputs.issues }}

  debug:
    name: Debug action event webhook
    runs-on: ubuntu-latest
    steps:
    - uses: JasonEtco/smee-action@v2
      with:
        channel: mondeja
